# Generated by Django 4.1.1 on 2022-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='news',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='weather',
            field=models.BooleanField(default=True),
        ),
    ]
