# Generated by Django 4.1.1 on 2022-10-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_clock', '0002_alter_alarm_news_alter_alarm_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='timestamp_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
